name: WaledNet
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  provider: ^6.1.2
  flutter_v2ray: ^1.0.10
  http: ^1.4.0
  google_fonts: ^6.2.1
  url_launcher: ^6.2.6
  cupertino_icons: ^1.0.6
  package_info_plus: ^8.3.0
  unity_ads_plugin: ^0.3.26
  shared_preferences: ^2.2.3
  dio: ^5.4.3+1
  firebase_core: ^2.28.0
  firebase_messaging: ^14.8.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/

  fonts:
    - family: CustomIcons
      fonts:
        - asset: assets/fonts/CustomIcons.ttf
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
        # - asset: assets/fonts/Montserrat-Bold.ttf
        #   weight: 700


